- src/App/Nav/links.ts
- src/Pages/Home/Home.tsx
- src/Pages/Overview/Overview.tsx
- update spec link to docs spec
- add docs link
- learn more -> https://docs.openfeature.dev/docs/reference/intro
- remove roadmap
- top bar order is: 
[Overview](https://openfeature.dev/overview)
[Documentation](https://docs.openfeature.dev/)
[Specification](https://docs.openfeature.dev/docs/specification/)
[Community](https://github.com/open-feature/community)
[GitHub](https://github.com/open-feature)
- update Mission statement
Closes: https://github.com/open-feature/openfeature.dev/issues/9
> feat: make docs live

- src/App/Nav/links.ts
This PR:
- Resolves #11 
Signed-off-by: agardnerit <adam@agardner.net>
> add slack link

- src/App/Footer/Footer.tsx
Signed-off-by: Justin Abrahms <jabrahms@ebay.com>
> Keep the LF happy and link off to their trademark info.

- src/App/Nav/Nav.tsx
resolve https://github.com/open-feature/openfeature.dev/issues/22
> Accessibility add link name

- docs/reference/concepts/03-evaluation-context.mdx
updates spec submodule to v0.6.0
> chore: update spec to v0.6.0

- src/datasets/providers/goff.ts
Add go feature flag client side provider
> feat: Add go feature flag client side provider

- src/components/ClientTechnologiesFeatures/WebFeatures/index.tsx
feat: Add flagd and goff web providers
> feat: Add flagd and goff web providers

- docs/reference/concepts/02-provider.mdx
- added multi-privders field on providers doc page.
Fixes #181
> added multi-provider support field

- src/datasets/providers/split.ts
Fix the incorrect link to https://github.com/splitio/split-openfeature-provider-go
Fixes #216
> fix: update link of split-openfeature-provider-go

- docs/reference/intro.mdx
reducing the use of the word standard as requested by the CNCF
> docs: Update intro.mdx

- docusaurus-ts-config.ts
reducing the use of the word standard as requested by the CNCF
> docs: Update docusaurus-ts-config.ts

- docs/tutorials/five-minutes-to-feature-flags.md
* use SDK in-memory provider
* add targeting example
> feat: update five-minutes-to-feature-flags

- src/datasets/providers/devcycle.ts
Adding DevCycle's new Web Provider.
> feat: add DevCycle Web Provider

- src/datasets/providers/index.ts
- Update Ecosystem titles to include the technology and category:
> feat: update ecosystem titles to include technology and category

- src/datasets/providers/goff.ts
- adds python and kotlin providers.
> feat(goff): add new providers for GO Feature Flag

- docs/reference/technologies/sdk-compatibility.mdx
- Fix commonly used paradigm for client-side SDK in doc
> [DOC] Fix commonly used paradigm for client-side SDK in doc

- docusaurus-ts-config.ts
- src/partials/features-zigzag.tsx
Last week, OpenFeature was accepted as an incubating project. This PR updates the documentation to reflect that.
> chore: update references from sandbox to incubating

- docs/tutorials/ofo.md
Update K8s example to match the latest OpenFeature Operator release
> feat: update k8s example

- docs/tutorials/ofo.md
Improving the wording, and making it consistent with new CRDs, and CR instances in latest end-to-end.yaml.
> chore: improve tutorial

- docusaurus.config.ts
- expands the OpenFeature description to include support for "in-house solutions"
I received feedback that a user was unaware that OpenFeature was built to work with in-house solutions. This copy is found later on the page but not "above the fold".
> chore: update OpenFeature description

- yarn.lock
Fixing vulns found with `yarn audit`
> chore: yarn audit fixes

- .github/workflows/update-sdk-docs.yaml
- adds GH workflow to 
Fixes #307
This was tested on my fork. CI runs can be seen [here](https://github.com/beeme1mr/openfeature.dev/actions/workflows/update-sdk-docs.yaml) and an example PR can be seen [here](https://github.com/beeme1mr/openfeature.dev/pull/1).
> ci: add GH workflow that updates sdk readmes

- src/datasets/providers/flipt.ts
- adds Node.JS Flipt Provider
https://deploy-preview-371--openfeature.netlify.app/ecosystem?instant_search%5BrefinementList%5D%5Btechnology%5D%5B0%5D=JavaScript&instant_search%5BrefinementList%5D%5Bvendor%5D%5B0%5D=Flipt
> Add NodeJS Flipt Provider

- src/datasets/providers/featbit.ts
- adds node FeatBit provider
- adds web FeatBit provider
Fixes #377, #378 
https://deploy-preview-382--openfeature.netlify.app/ecosystem?instant_search%5BrefinementList%5D%5Bvendor%5D%5B0%5D=FeatBit
> Add node and web FeatBit providers

- docs/reference/concepts/01-evaluation-api.mdx
- docs/reference/concepts/02-provider.mdx
- docs/reference/concepts/03-evaluation-context.mdx
- docs/reference/concepts/04-hooks.mdx
- docs/reference/intro.mdx
- package.json
- src/css/custom.css
- yarn.lock
- adds this new feature
Fixes https://github.com/open-feature/openfeature.dev/issues/383
example https://github.com/facebook/docusaurus/blob/main/website/docs/introduction.mdx#L55
> chore: fix iframe video on mobile

- src/datasets/providers/devcycle.ts
- Adds DevCycle's PHP Provider to the listings
> Add DevCycle PHP Provider

- src/datasets/providers/devcycle.ts
- Adds DevCycle Python provider card
> Add DevCycle Python provider

- blog/2024-02-28-reconciling-with-state.md
> fix: spelling

- docs/tutorials/getting-started/go.mdx
- Fixes GO tutorial example to use `SetProviderAndWait()`
- Fixes #299
> fix: go tutorial to use `SetProviderAndWait()`

- docs/tutorials/getting-started/java.mdx
- Updates Java tutorial to use `setProviderAndWait()`
- #299
> chore: update Java tutorial to use `setProviderAndWait()`

- CONTRIBUTING.md
- adds documentation on the submodule command.
- updates the minium documented node version.
> chore: improve contributing guide

- src/datasets/providers/flagsmith.ts
Adds the newly added [Flagsmith JS Client Provider](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/flagsmith-client).
> chore: Add Flagsmith JS Client

- docs/tutorials/ofo.md
Update tutorials document
- remove manual create namespace section. this has been part of `release.yaml`
- move downloading `end-to-end.yaml` below to be more logic
- state example is using "default" but it is up to user to pick the one they want
- fix wrong term which should refer to CR not CRD
> docs: update tutorials

- docs/reference/concepts/03-evaluation-context.mdx
- docs/reference/concepts/06-sdk-paradigms.mdx
> Fixed some typos

- .github/workflows/update-sdk-docs.yaml
Updates the SDK doc update action to use a PAT. This should trigger the PR verification actions automatically.
> ci: run CI actions after update sdk doc change

- netlify.toml
> chore: add ofo tutorial redirect

- src/datasets/providers/goff.ts
- Adding swift SDK for go-feature-flag
> feat: Adding swift SDK for go-feature-flag

- blog/2024-07-18-wearedevelopers-24.md
- Updates release date of wearedevelopers blog
> fix: Update date of wearedevelopersblog

- src/datasets/providers/kameleoon.ts
Add Kameleoon as a Java OpenFeature Provider
> Adding Java KameleoonProvider

- docs/tutorials/open-feature-operator/quick-start.md
> doc: fix shell command

- blog/2022-07-06-external-posts.md
- blog/2023-10-19-renaming-js-sdk.md
Fixed posts that are displayed during build
> chore: add truncation markers to blog posts

- src/datasets/sdks/web.ts
- updates the path to the web readme
Update the doc generated to use the updated file path.
Run `yarn run update:sdk-docs`
> chore: update web doc path

- CONTRIBUTING.md
- adds an ecosystem section in the contribs doc
> add ecosystem section to contrib doc

- .github/workflows/dco-merge-group.yaml
- renovate.json
Updates the configuration to leverage a shared Renovate config.
> ci: migrate renovate config

- blog/2024-09-19-kubecon-na-24.md
preview: https://deploy-preview-696--openfeature.netlify.app/blog/kubeconna24
> docs(blog): add KubeCon NA teaser blog

- src/datasets/providers/kameleoon.ts
Added Kameleoon providers for: Go / Kotlin (Android) / Python
> Added Kameleoon providers for: Go / Kotlin (Android) / Python

- docusaurus.config.ts
- update announcement bar with openFeature summit
Fixes #778
> chore: update announcement bar with openFeature summit

- src/datasets/providers/kameleoon.ts
Added Kameleoon provider for: iOS (Swift)
> Add Kameleoon Provider for Swift

- package.json
- yarn.lock
resolve https://github.com/open-feature/openfeature.dev/issues/794
> chore: update docusaurus

- src/datasets/support/commercial-support.ts
Added link Kameleoon & Openfeature commercial page.
> Added link Kameleoon & Openfeature commercial page.

- src/datasets/providers/kameleoon.ts
Hello OpenFeature Team,
Wishing you all a Merry Christmas and a Happy New Year!
I’ve added links for the OpenFeature Kameleoon provider for JavaScript and Node.js.
Thanks!
> Added links for Openfeature Kameleoon provider for JS / NodeJS

- src/datasets/providers/unleash.ts
adds the unleash web provider for JS
- adds this new feature
Closes #901 
pending merge of this PR into js-sdk-contrib - https://github.com/open-feature/js-sdk-contrib/pull/1105
n/a
n/a
> added unleash web JS provider

- docusaurus.config.ts
- adds BlueSky to social media community list
> feat: add BlueSky to social media community list

- src/datasets/providers/flipt.ts
- adds the Flipt Python provider
Fixes #932
> chore: add flipt python provider

- src/datasets/providers/tggl.ts
> chore: add Tggl .NET provider

- src/pages/ecosystem.tsx
- update technology filter's size on ecosystems page to include React
> chore: update technology filter size to include React

- package.json
- src/pages/ecosystem.tsx
- yarn.lock
- regenerates lock file to remove duplicate React types
- cast the instance search client type
> regenerate lock, cast type issue

- src/datasets/providers/devcycle.ts
- Adds DevCycle NestJS Provider Docs
> feat: add DevCycle NestJS docs

- docs/tutorials/getting-started/rust.mdx
- adds Rust tutorial with Axum for flagd
> doc: Add rust with axum tutorial

- src/datasets/providers/devcycle.ts
- Adds DevCycle's Ruby Provider
> feat: add DevCycle Ruby Provider

- src/datasets/index.ts
- src/datasets/ofrep-api/devcycle.ts
- src/datasets/ofrep-api/flagd.ts
- src/datasets/ofrep-api/flipt.ts
- src/datasets/ofrep-api/goff.ts
- src/datasets/ofrep-api/index.ts
- src/datasets/types.ts
- src/partials/ecosystem/hit.tsx
- Adds a section to the Ecosystems page for listing the OFREP API compatible vendors/projects.
> feat: add OFREP API section to Ecosystem page

- blog/2025-03-19-devcycle-march-hackathon.md
- fixes small grammar issues on devcycle blog post
> fix: small grammar issues on devcycle blog post

- blog/2023-05-24-spec-0-6-0.md
- docs/reference/concepts/02-provider.mdx
- src/datasets/providers/multi-provider.ts
- Documentation updates for the multi-provider.
- providing clarity between domain-scoped multiple providers + clients and mutli-provider
> feat: multi-provider docs updates

- src/datasets/providers/growthbook.ts
- adds Go and .NET technologies to GrowthBook provider
Fixes #1130 #1102
> feat: add Go and .NET technologies to GrowthBook provider

- src/datasets/providers/bucketeer.ts
- adds Bucketeer JS Client Provider
Fixes #1216
> chore: add Bucketeer JS Client Provider

- src/datasets/providers/ofrep.ts
> doc: Add dotnet OFREP provider

- src/datasets/providers/bucketeer.ts
- adds Bucketeer Koltin and Go Provider
Fixes #1218 #1220
> Add Bucketeer Koltin and Go Providers

- docs/tutorials/open-feature-cli.md
Add OpenFeature CLI tutorial and setup instructions.
Fixes #1137
> docs: add OpenFeature CLI tutorial and setup instructions
