src/components/custom/tutorial/flagd-content.mdx
adds a warning about running flagd using Windows and docker
=> chore: add info on windows+docker limits

docusaurus.config.js
Adds the OF YT page to the Community section of the footer
=> Add YouTube to footer of docusaurus.config.js

blog/2023-06-22-openfeature-adoption-story.md, blog/authors.yml
Add blog post: OpenFeature Adoption Story.
- Open the OpenFeature Blog page with all blogs, see the new blog post looks as expected and truncated.
- Press on the new blog post, see new blog post looks as expected.
=> blog: add openfeature adoption story post

src/components/ServerTechnologiesFeatures/GoFeatures/index.tsx, src/datasets/providers/configcat.ts
- adds the ConfigCat Go provider to the docs
Thank you, @rcowe, for your contribution.
The provider configuration should be in a central location. A [follow-up issue](https://github.com/open-feature/openfeature.dev/issues/154) will consolidate the provider and hook data set.
Open the preview and look for the ConfigCat provider on the ecosystem page and under the Go SDK.
=> add configcat go provider

docs/tutorials/getting-started/php.mdx
- fixes the client variable
Fixes #72
=> fix: typo in php tutorial

blog/authors.yml
adds Jake Van Vorhis (@jakedoublev) to the blog authors list (for an upcoming blog post).
=> add Jake Van Vorhis to authors.yml

docusaurus-ts-config.ts
- adds google analytics with anonymized IP enabled
Access to the account is available to the Governance Committee and the CNCF. Read access can be granted on case-by-case bases by contacting a member of the GC.
=> feat: add google analytics

docs/reference/concepts/05-events.mdx, docs/reference/intro.mdx
- adds event description to intro
Updated the event file extension to `.mdx` to match the other files.
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> docs: add event description to intro

src/datasets/providers/devcycle.ts
Adding a reference to the DevCycle Java Provider to the Openfeature.dev site so that it appears in the ecosystem of providers
Fixes #266
The DevCycle Java Provider is built directly into the DevCycle Java SDK and not a separate repo, so the link goes to the `DevCycleHQ/java-server-sdk` repo
* Run `yarn start`
* Go to the Ecosystems page
* Filter by DevCycle to confirm the Java provider appears
=> Adding DevCycle Java Provider

src/datasets/providers/devcycle.ts
Adding a reference to the DevCycle Go and .NET Providers to the Openfeature.dev site so that they appear in the ecosystem of providers.
I didn't create an issue for either of these providers, but I can do that if that's a necessary step for adding them.
- Run `yarn start`
- Go to the Ecosystems page
- Filter by DevCycle to confirm the Go and .NET providers appear
=> Add Go and .NET DevCycle providers

docs/reference/concepts/02-provider.mdx
Adds FAQ for disabled reason vs disabled error.
Direct preview: https://deploy-preview-275--openfeature.netlify.app/docs/reference/concepts/provider#why-isnt-there-an-error-code-for-disabled-flags
=> docs: add FAQ about disabled flags

docs/tutorials/ofo.md, static/samples/kind-cluster.yaml
Support for client-side flags in cloud native demo.
[This](https://github.com/open-feature/playground/pull/267) must be merged first (draft until then).
=> feat: ui flags in cloud native demo

scripts/sdk-compatibility-generator.ts
- update readme parser to support markdown tags
This PR adds support for markdown readmes that don't use HTML. This change was introduced because some package hosting services don't support HTML in markdown.
=> Update readme parser to support markdown tags

docs/tutorials/getting-started/go.mdx, docs/tutorials/getting-started/java.mdx, docs/tutorials/getting-started/php.mdx, src/components/custom/tutorial/flagd-change-content.mdx
This adds colored diff output to all existing tutorials matching the format used for the Node tutorial. Looks much easier to read and does not interfere with copy-paste.
=> docs: improve syntax highlighting for tutorial code examples

src/datasets/providers/flagsmith.ts
Adding a reference to the Flagsmith .Net Provider to the Openfeature.dev site so that it appears in the ecosystem of providers
- Run yarn start
- Go to the Ecosystems page
- Filter by Flagsmith to confirm the .Net provider appears
=> Adding Flagsmith Dotnet Provider

renovate.json
- disables automerging
A recent minor update to Docusarus broke CSS styling. This was automatically merged by Renovate. Since we don't have visual tests in place, we should disable automerging so we can double-check the preview.
=> chore: disable automerge

src/datasets/providers/flagd.ts
`flagd`'s Python provider seems to be missing on the website. Adding it here.
=> Add flagd Python provider to the ecosystem dataset

src/datasets/providers/devcycle.ts
- Fixed link to DevCycle Java Provider docs
=> fix: DevCycle Java provider link

docs/tutorials/getting-started/go.mdx
This pull request removes the deprecated go package `github.com/open-feature/go-sdk/pkg/openfeature` and includes minor documentation improvements. The changes include:
- Importing `github.com/open-feature/go-sdk/openfeature` due to `github.com/open-feature/go-sdk/pkg/openfeature` is deprecated from SDK
- Running `go get github.com/open-feature/go-sdk/openfeature` to fetch the SDK.
- Adding missing imports
- Minor go improvements
Files Modified
- `openfeature.dev/docs/tutorials/getting-started/go.mdx`
1. Pull down this branch.
2. Compile and run locally
3. Follow the instructions and steps to generate go implementation
=> fix: update go tutorial removing deprecated openfeature sdk

blog/2023-02-06-catering-to-the-client-side.md
- updates the blog to use the release package names
The phrasing of the blog makes it clear that we hadn't settled on a package name but I think it's valuable to update the names now that we have.
=> chore: update the npm package names

blog/april-2023-update, docusaurus.config.ts
This pull request fixes broken links in the [docusaurus.config.ts](https://github.com/open-feature/openfeature.dev/blob/0b8948b33ad5b0cee8111aaf9fb7cdb582fc3991/docusaurus.config.ts#L136) file and blog entry. The link previously pointed to https://www.youtube.com/@openfeature834, but the URL has changed.
- fix broken link to https://www.youtube.com/@openfeature
=> doc: update broken link for youtube channel 

src/datasets/providers/env-var.ts, src/datasets/providers/flipt.ts, src/datasets/types.ts
This commit adds support for rust types to the ecosystem page.
- [add rust support to Technology type](https://github.com/jbovet/openfeature.dev/commit/308f6001ce796e0f4488cfdf4f746f6938c0d780)
- [add rust Flipt provider](https://github.com/jbovet/openfeature.dev/commit/7849596ca13d2d1561f782eae1a7cdcfdf597811) thanks @tamaroning
- [add rust env-var provider](https://github.com/jbovet/openfeature.dev/commit/260a072ece545f6875829da1a2a884d5d2267fb8)
- [fix: keep alphabetical list](https://github.com/open-feature/openfeature.dev/pull/579/commits/3ceac3b438afe7e6acc8b8d286001c08d40f5559)
related to #530 #559
=> Doc adds support for rust types and providers to the ecosystem page.

blog/2024-06-14-multi-provider-release.md, blog/authors.yml
Adds a blog post introducing the new Multi-Provider in JavaScript and Node.js 
This shouldn't be merged before the [client-side multi-provider PR](https://github.com/open-feature/js-sdk-contrib/pull/942) is merged, as it references the client-side provider
=> Add multi-provider blog post

docs/tutorials/getting-started/python.mdx
- Added missing `openfeature-sdk` install command.
=> docs: add missing install command in the Python tutorial

src/datasets/providers/goff.ts
Waiting for the PR https://github.com/open-feature/ruby-sdk-contrib/pull/38 to be merged and after we can add the provider to the ecosystem page.
=> feat(GOFF): Add Ruby provider to the ecosystem page

src/datasets/providers/bucket.ts
- adds the Bucket Web Provider to ecosystem pages
Similar to #674 
Tested locally
=> Add bucket web provider to ecosystem

blog/2023-02-06-catering-to-the-client-side.md
Thank you for the project!
Spelling fixings for https://openfeature.dev/blog/catering-to-the-client-side/ (Catering to the client side):
- Initally -> Initially
- Feburary -> February
- the the -> the
=> chore(catering-to-the-client-side) Typo corrections

docusaurus.config.ts
Removing the KubeCon announcement banner.
=> chore: remove announcement bar

src/datasets/providers/growthbook.ts
- add Growthbook node provider
Fixes #919
https://deploy-preview-922--openfeature.netlify.app/ecosystem?instant_search%5BrefinementList%5D%5Bvendor%5D%5B0%5D=GrowthBook
FYI @msamper
=> feat: add Growthbook node provider

src/datasets/providers/devcycle.ts, src/datasets/sdks/react.ts, src/datasets/types.ts
- Adds a link to DevCycle's React provider docs
- Adds React as its own technology section.
Even though the OpenFeature React SDK uses the same Javascript Web providers for all providers, certain providers may want to provide specific install instructions for React and customize the setup for their providers. For example, at DevCycle we are updating our providers and docs so we can identify when a customer is using the DevCycle provider with the OpenFeature React SDK instead of the OpenFeature Web SDK.
(We will also likely do a similar thing for the NestJS SDK)
=> feat: add DevCycle react provider docs, add React as a technology

src/pages/ecosystem.tsx
- Updates the sort order of the `Technology` and `Vendor` filters to be based on the count of the number of providers. This could help encourage vendors to increase their number of supported platforms.
- The technology section we could keep by name, but I also think there is a directional signal by seeing there are ~40 Javascript providers and only 3 for Rust.
=> chore: update ecosystem page ordering based on count

src/datasets/constants.ts, src/datasets/hooks/index.ts, src/datasets/index.ts, src/datasets/providers/devcycle.ts, src/datasets/providers/goff.ts, src/datasets/providers/index.ts, src/datasets/sdks/angular.ts, src/datasets/sdks/ecosystem.ts, src/datasets/sdks/index.ts, src/datasets/sdks/nestjs.ts, src/datasets/sdks/react.ts, src/datasets/types.ts, src/pages/ecosystem.tsx, src/partials/ecosystem/hit.tsx
- Updates the `Technology` section to have child technology SDKs like `React`, `Angular`, `NestJS` show in the Technology list.
- When a child technology like `React` is selected, it will show the React SDK, all providers from a vendor marked as their `React` provider (and exclude their base Web provider), and all other vendors' web providers.
- For Vendors to add specific docs for a child technology Provider like `React` they just need to set their `technology` and `parentTechnology` as so: 
```
{
...
technology: 'React',
parentTechnology: 'JavaScript',
}
```
- These updates are mostly handled through adding an `allTechnologies` field that lists the multiple technologies a provider should be filterable for. It does not add multiple records to the search hits.
- Updated the number of …
=> feat: update how react technology selection is handled

src/datasets/providers/growthbook.ts
- adds the GrowthBook Java Provider
Fixes #974 
The anchor in the web provider is not longer valid. Is there another ULR we should us?
=> chore: add GrowthBook Java Provider

docs/reference/concepts/02-provider.mdx, docs/reference/concepts/03-evaluation-context.mdx, docs/reference/concepts/04-hooks.mdx, docs/reference/concepts/05-events.mdx, docs/reference/concepts/06-sdk-paradigms.mdx, docs/reference/concepts/07-tracking.mdx
Updates the tracking docs page with more context, use cases and example code.
Address [DOC] Add event tracking #756
- This update also fixes a little bit of the docusaurus sidebar metadata where position was all being set statically to 1
N/A
N/A
=> Tracking docs update

src/datasets/hooks/sentry.ts
- follow up from this PR which adds the JS Sentry hook: https://github.com/open-feature/openfeature.dev/pull/1043
- Sentry also has a Python hook available, documented here: https://docs.sentry.io/platforms/python/configuration/integrations/openfeature/
- relates to https://github.com/getsentry/team-replay/issues/560
- original thread: https://github.com/getsentry/sentry/discussions/73542#discussioncomment-12502060
=> feat: add Sentry python hook to ecosystem page

blog/2025-03-20-vercel-flags-sdk.md, blog/2025-03-25-sentry-openfeature-integration.md
- add missing `truncate` tag on vercel blog
=> fix: add truncate tag to vercel blog

src/datasets/providers/devcycle.ts
- Adds DevCycle's iOS Provider to the Ecosystem page.
=> feat: adding DevCycle iOS Provider to Ecosystem

docs/reference/concepts/02-provider.mdx
Typo: Scopped -> Scoped
- Fixes a typo in the Provider documentation
=> Fix typo in provider MD

docs/tutorials/getting-started/java/_category_.json, docs/tutorials/getting-started/java/dropwizard.mdx, docs/tutorials/getting-started/java/spring-boot.mdx, renovate.json
Both Spring Boot and Dropwizard are examples of using OpenFeature in a Java framework, adding a top level section for Java SDK with Spring Boot and Dropwizard as examples.
~Create documentation of how to integrate OpenFeature Java SDK in Dropwizard using the `InMemoryProvider` either via the SDK only, or using the dropwizard-openfeature module.~
Create documentation on how to integrate OpenFeature Java SDK into Dropwizard either by using the SDK directly, or the https://github.com/sideshowcoder/dropwizard-openfeature module. In either case using `flagd` as the provider of flags, with the shared content from the Spring Boot tutorial.
=> Add Dropwizard OpenFeature Guide

docs/tutorials/open-feature-operator/advanced-topics.md, static/samples/nginx-config.yaml
The OFO client-side demo is broken due to a breaking change (bug?) in the NGINX controller. This provides a workaround.
See: https://github.com/kubernetes/ingress-nginx/issues/11176
=> fix: OFO demo workaround for nginx change(bug)

src/datasets/providers/devcycle.ts
- Adds DevCycle Kotlin / Android SDK to Ecosystem page
=> docs: add devcycle kotlin / android SDK
